export const assetSchemas = {
  Desktop: [
    { key: "User", label: "User", type: "text" },
    { key: "Department", label: "Department", type: "text" },
    { key: "Computer Name", label: "Computer Name", type: "text" },
    { key: "Make", label: "Make", type: "text" },
    { key: "Model", label: "Model", type: "text" },
    { key: "S/N", label: "S/N", type: "text" },
    { key: "CPU", label: "CPU", type: "text" },
    { key: "GPU", label: "GPU", type: "text" },
    { key: "RAM", label: "RAM", type: "text" },
    { key: "Storage", label: "Storage", type: "text" },
    { key: "OS", label: "OS", type: "text" },
    { key: "OS Key", label: "OS Key", type: "text" },
    { key: "Monitor Make", label: "Monitor Make", type: "text" },
    { key: "Monitor Model", label: "Monitor Model", type: "text" },
    { key: "Monitor S/N", label: "Monitor S/N", type: "text" },
    { key: "Monitor Size", label: "Monitor Size", type: "text" },
    { key: "Keyboard Make", label: "Keyboard Make", type: "text" },
    { key: "Keyboard Model", label: "Keyboard Model", type: "text" },
    { key: "Keyboard S/N", label: "Keyboard S/N", type: "text" },
    { key: "Mouse Make", label: "Mouse Make", type: "text" },
    { key: "Mouse Model", label: "Mouse Model", type: "text" },
    { key: "Mouse S/N", label: "Mouse S/N", type: "text" },
  ],
  Laptops: [
    { key: "User", label: "User", type: "text" },
    { key: "Department", label: "Department", type: "text" },
    { key: "Computer Name", label: "Computer Name", type: "text" },
    { key: "Make", label: "Make", type: "text" },
    { key: "Model", label: "Model", type: "text" },
    { key: "Model Number", label: "Model Number", type: "text" },
    { key: "Service Tag(S/N)", label: "Service Tag(S/N)", type: "text" },
    { key: "RAM", label: "RAM", type: "text" },
    { key: "Processor", label: "Processor", type: "text" },
    { key: "Storage", label: "Storage", type: "text" },
    { key: "OS", label: "OS", type: "text" },
  ],
  Mobile: [
    { key: "User", label: "User", type: "text" },
    { key: "Department", label: "Department", type: "text" },
    { key: "Make", label: "Make", type: "text" },
    { key: "Model", label: "Model", type: "text" },
    { key: "Model Number", label: "Model Number", type: "text" },
    { key: "S/N", label: "S/N", type: "text" },
    { key: "IMEI1", label: "IMEI1", type: "text" },
    { key: "IMEI2", label: "IMEI2", type: "text" },
    { key: "RAM", label: "RAM", type: "text" },
    { key: "ROM", label: "ROM", type: "text" },
    { key: "OTP Mobile Number", label: "OTP Mobile Number", type: "text" },
    { key: "Color", label: "Color", type: "text" },
    { key: "OS", label: "OS", type: "text" },
    { key: "Google/Apple Account", label: "Google/Apple Account", type: "text" },
  ],
  Printer: [
    { key: "Location/Dept", label: "Location/Dept", type: "text" },
    { key: "User", label: "User", type: "text" },
    { key: "Make", label: "Make", type: "text" },
    { key: "Model", label: "Model", type: "text" },
    { key: "Model Number", label: "Model Number", type: "text" },
    { key: "S/N", label: "S/N", type: "text" },
  ],
  POS: [
    { key: "Location", label: "Location", type: "text" },
    { key: "Computer Name", label: "Computer Name", type: "text" },
    { key: "Make", label: "Make", type: "text" },
    { key: "Model", label: "Model", type: "text" },
    { key: "Model Number", label: "Model Number", type: "text" },
    { key: "S/N", label: "S/N", type: "text" },
    { key: "Part #", label: "Part #", type: "text" },
    { key: "CPU", label: "CPU", type: "text" },
    { key: "RAM", label: "RAM", type: "text" },
    { key: "Storage", label: "Storage", type: "text" },
    { key: "OS", label: "OS", type: "text" },
    { key: "OS Key", label: "OS Key", type: "text" },
    { key: "Office Key", label: "Office Key", type: "text" },
    { key: "Keyboard Make", label: "Keyboard Make", type: "text" },
    { key: "Keyboard Model", label: "Keyboard Model", type: "text" },
    { key: "Keyboard S/N", label: "Keyboard S/N", type: "text" },
    { key: "Barcode Scanner Model", label: "Barcode Scanner Model", type: "text" },
    { key: "Barcode Scanner S/N", label: "Barcode Scanner S/N", type: "text" },
  ],
  "Bill Printer": [
    { key: "Location", label: "Location", type: "text" },
    { key: "User", label: "User", type: "text" },
    { key: "Make", label: "Make", type: "text" },
    { key: "Model", label: "Model", type: "text" },
    { key: "Model Number", label: "Model Number", type: "text" },
    { key: "S/N", label: "S/N", type: "text" },
  ],
  "Weighing Scale": [
    { key: "Location", label: "Location", type: "text" },
    { key: "Make", label: "Make", type: "text" },
    { key: "Model", label: "Model", type: "text" },
    { key: "S/N", label: "S/N", type: "text" },
    { key: "Scale Machine IP Address", label: "Scale Machine IP Address", type: "text" },
    { key: "Status", label: "Status", type: "text" },
    { key: "QTY", label: "QTY", type: "number" },
  ],
  Biometric: [
    { key: "Store Name", label: "Store Name", type: "text" },
    { key: "Model Number", label: "Model Number", type: "text" },
    { key: "STATUS", label: "STATUS", type: "text" },
  ],
  Switch: [
    { key: "Location", label: "Location", type: "text" },
    { key: "User", label: "User", type: "text" },
    { key: "Make", label: "Make", type: "text" },
    { key: "Model", label: "Model", type: "text" },
    { key: "Model Number", label: "Model Number", type: "text" },
    { key: "S/N", label: "S/N", type: "text" },
  ],
  Router: [
    { key: "Location", label: "Location", type: "text" },
    { key: "User", label: "User", type: "text" },
    { key: "Make", label: "Make", type: "text" },
    { key: "Type", label: "Type", type: "text" },
    { key: "Model", label: "Model", type: "text" },
    { key: "Model Number", label: "Model Number", type: "text" },
    { key: "S/N", label: "S/N", type: "text" },
    { key: "IMEI(if 4G)", label: "IMEI(if 4G)", type: "text" },
  ],
};
